# Generated by Django 5.2.3 on 2025-06-17 15:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_seats', models.PositiveSmallIntegerField(verbose_name='Количество мест')),
                ('free', models.BooleanField(default=True, verbose_name='Доступность столика')),
            ],
            options={
                'verbose_name': 'Столик',
                'verbose_name_plural': 'Столики',
                'ordering': ['free'],
            },
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата, на которую забронирован столик')),
                ('time', models.TimeField(verbose_name='Время, на которое забронирован столик')),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservation', to=settings.AUTH_USER_MODEL, verbose_name='Гость')),
                ('table', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='restaurant.table', verbose_name='Забронированный столик')),
            ],
            options={
                'verbose_name': 'Бронь',
                'verbose_name_plural': 'Брони',
                'ordering': ['date'],
            },
        ),
    ]
