# Generated by Django 5.2.3 on 2025-06-18 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("restaurant", "0002_reservation_comment"),
    ]

    operations = [
        migrations.AddField(
            model_name="table",
            name="image",
            field=models.ImageField(null=True, upload_to="restaurant/images", verbose_name="Изображение столика"),
        ),
        migrations.AddField(
            model_name="table",
            name="number",
            field=models.PositiveIntegerField(null=True, verbose_name="Номер столика"),
        ),
    ]
