# Generated by Django 5.2.3 on 2025-06-19 15:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0003_table_image_table_number'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30, verbose_name='Имя сотрудника')),
                ('last_name', models.CharField(max_length=50, verbose_name='Фамилия сотрудника')),
                ('position', models.CharField(choices=[('Владелец', 'Владелец'), ('Управляющий', 'Управляющий'), ('Шев-повар', 'Шев-повар'), ('Су-шеф', 'Су-шев'), ('Повар', 'Повар'), ('Администратор зала', 'Администратор зала'), ('Официант', 'Официант'), ('Бармен', 'Бармен')], max_length=20, verbose_name='Должность')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='restaurant/workers/images', verbose_name='Фото сотрудника')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание сотрудника')),
            ],
        ),
        migrations.AddField(
            model_name='reservation',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Бронь активна'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservation', to=settings.AUTH_USER_MODEL, verbose_name='Гость'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='table',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='restaurant.table', verbose_name='Забронированный столик'),
        ),
        migrations.AlterField(
            model_name='table',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='restaurant/images', verbose_name='Изображение столика'),
        ),
    ]
