# Generated by Django 5.2.3 on 2025-06-25 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("restaurant", "0007_alter_table_image_alter_worker_avatar"),
    ]

    operations = [
        migrations.AddField(
            model_name="reservation",
            name="reminder_sent",
            field=models.BooleanField(default=False, verbose_name="Напоминание отправлено"),
        ),
    ]
